- name: Installer Docker
  raw: yum install -y docker

- name: Démarrer Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Déployer le conteneur PHP-FPM
  docker_container:
    name: php-fpm
    image: php:7.4-fpm
    state: started
